server:
  port: 8080

huron:

  filter:
    type: ${FILTER_TYPE:none}
    redis:
      host: ${FILTER_REDIS_HOST:localhost}
      port: ${FILTER_REDIS_PORT:6379}

  storage:
    rectifier: ${STORAGE_RECTIFIER:rabbit}
    kafka:
      servers: ${STORAGE_KAFKA_SERVERS:localhost:9092}
    rabbit:
      host: ${STORAGE_RABBIT_HOST:localhost}
      port: ${STORAGE_RABBIT_PORT:5672}
      user-name: ${STORAGE_RABBIT_USERNAME:admin}
      password: ${STORAGE_RABBIT_PASSWORD:admin}